spring:
  datasource:
    url: jdbc:postgresql://172.17.0.2:5432/livraria
    username: postgres
    password: mysecretpassword
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
jwt:
  expiration:
  secret:
